/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrcCheckRouteImport } from './routes/prc-check'
import { Route as RecommendationRouteImport } from './routes/recommendation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrcCheckRoute = PrcCheckRouteImport.update({
  id: '/prc-check',
  path: '/prc-check',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationRoute = RecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prc-check': typeof PrcCheckRoute
  '/recommendation': typeof RecommendationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prc-check': typeof PrcCheckRoute
  '/recommendation': typeof RecommendationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prc-check': typeof PrcCheckRoute
  '/recommendation': typeof RecommendationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prc-check' | '/recommendation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prc-check' | '/recommendation'
  id: '__root__' | '/' | '/prc-check' | '/recommendation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrcCheckRoute: typeof PrcCheckRoute
  RecommendationRoute: typeof RecommendationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prc-check': {
      id: '/prc-check'
      path: '/prc-check'
      fullPath: '/prc-check'
      preLoaderRoute: typeof PrcCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation': {
      id: '/recommendation'
      path: '/recommendation'
      fullPath: '/recommendation'
      preLoaderRoute: typeof RecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrcCheckRoute: PrcCheckRoute,
  RecommendationRoute: RecommendationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
