import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Building2, Check, CheckCircle2, ChevronRight, CircleDollarSign, Clipboard, Copy, FileText, Landmark, Mail, Route, ShieldCheck, Timer, UserRound, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";
import { SectionHeading, StatusBadge } from "./shared";

const immediate = { title: "Payoneer → Meezan", reason: "Best fit for this payment because it's due today and you already have this setup available.", route: ["UK Client", "Payoneer", "Meezan Bank"] };
const optimal = { title: "Meezan Freelancer Account + ESFCA", reason: "Better for recurring IT export income because it matches your foreign-currency goal, Islamic banking preference and documentation needs.", route: ["UK Client", "Bank transfer", "Meezan Freelancer + ESFCA"] };

export function RecommendationPage({ startsFlexible = false }: { startsFlexible?: boolean }) {
  const [flexible, setFlexible] = useState(startsFlexible);
  const [noFx, setNoFx] = useState(false);
  const [noIslamic, setNoIslamic] = useState(false);
  const [instructions, setInstructions] = useState(false);
  const [copied, setCopied] = useState<string>();
  const best = flexible ? optimal : immediate;
  const copy = (kind: string) => { setCopied(kind); window.setTimeout(() => setCopied(undefined), 1400); };
  return <div className="page-shell recommendation-page"><header className="payment-header"><div><p className="eyebrow">Payment analyzed</p><h1><span className="money">£2,500</span> · UK → Pakistan · Web Development</h1></div><div className="payment-actions"><Link to="/" className="text-action">Edit context</Link><button className="trust-button" type="button"><ShieldCheck /> Verified rules · Sep 12, 2026</button></div></header>
    {flexible && <div className="update-note" role="status"><CheckCircle2 /><span><strong>Recommendation updated</strong> because urgency is no longer the main constraint.</span></div>}
    <SectionHeading title="Best route for this payment" description="Ranked for your current timing, setup and preferences." />
    <div className={cn("recommendation-grid", flexible && "reranked")}><RouteCard kind="best" data={best} flexible={flexible} />{!flexible && <LongTermCard />}</div>
    <section className="section-block"><SectionHeading title="Why Raasta chose this" description="The recommendation changes when your situation changes." /><div className="reasoning-chain">{[
      ["Payment due today", "Speed matters most", Timer], ["Payoneer available", "No setup delay", WalletCards], ["Retain foreign currency", "Long-term goal", CircleDollarSign], ["Islamic banking", "Meezan preferred", Landmark], ["Best Now", flexible ? "Optimal setup" : "Available route", Route]
    ].map(([title, text, Icon], index) => <div className="reason-step" key={String(title)}><div><Icon /><span>{index + 1}</span></div><strong>{title as string}</strong><small>{text as string}</small>{index < 4 && <ChevronRight className="reason-arrow" />}</div>)}</div></section>
    <section className="section-block sensitivity"><SectionHeading title="What would change my recommendation?" description="Try a change to see how the ranking responds." /><div className="toggle-row"><ToggleChip selected={flexible} onClick={() => setFlexible(!flexible)}>I can wait 2 days</ToggleChip><ToggleChip selected={noFx} onClick={() => setNoFx(!noFx)}>I don't need to keep FX</ToggleChip><ToggleChip selected={noIslamic} onClick={() => setNoIslamic(!noIslamic)}>Islamic banking isn't required</ToggleChip></div>{(noFx || noIslamic) && <p className="sensitivity-note">These preferences affect the reasoning, but urgency remains the deciding factor in this mock scenario.</p>}</section>
    <Accordion type="multiple" className="info-accordions"><AccordionItem value="pakistan"><AccordionTrigger><span className="accordion-title">🇵🇰 Pakistan Context <small>Why local factors matter</small></span></AccordionTrigger><AccordionContent><PakistanContext /></AccordionContent></AccordionItem><AccordionItem value="cost"><AccordionTrigger><span className="accordion-title">Estimated Cost Breakdown <small>No fake precision</small></span></AccordionTrigger><AccordionContent><CostBreakdown /></AccordionContent></AccordionItem></Accordion>
    <section className="section-block"><SectionHeading title="Other routes worth knowing" description="Only the closest alternatives for this payment." /><div className="alternatives"><Alternative title="Lowest estimated cost" route="Direct bank transfer → freelancer account" consider="May reduce provider costs and create a direct banking record." notOne="Setup and intermediary charges are less predictable for today's payment." /><Alternative title="Client-friendly alternative" route="Client uses Wise → Pakistani personal account" consider="Convenient for the sender and familiar to many UK clients." notOne="It is less aligned with your foreign-currency and documentation priorities, and differs from holding Wise USD details." /></div></section>
    <section className="next-steps"><SectionHeading title="What should I do next?" description="A simple checklist for this payment." /><ol>{["Confirm the route", "Check your receiving account", "Send payment instructions to your client", "Save your invoice and payment proof", "Check the PRC/ePRC after the payment arrives"].map((item, index) => <li key={item}><span>{index + 1}</span><div><strong>{item}</strong><small>{["Use Payoneer → Meezan for the payment due today.", "Confirm the receiving details before sharing them.", "Use a clear invoice reference so the payment can be identified.", "Keep both together for your payment records.", "Compare the classification with the work you completed."][index]}</small></div></li>)}</ol><Button size="lg" onClick={() => setInstructions(true)}><Mail /> Generate Instructions for Client</Button></section>
    <p className="disclaimer">Raasta provides informational guidance only. Fees, timing, tax and regulatory outcomes depend on your account and circumstances and should be verified where needed.</p>
    <Sheet open={instructions} onOpenChange={setInstructions}><SheetContent className="instructions-drawer"><SheetHeader><SheetTitle>Client Payment Instructions</SheetTitle><SheetDescription>A ready-to-share mock message using placeholder details only.</SheetDescription></SheetHeader><div className="message-preview"><p>Hi Sarah, here's the recommended way to pay this invoice. Please use the payment details provided below and include the invoice reference so the payment can be identified correctly.</p><dl><div><dt>Payment method</dt><dd>Payoneer receiving details</dd></div><div><dt>Account name</dt><dd>YOUR NAME</dd></div><div><dt>Invoice reference</dt><dd className="money">INV-XXXX</dd></div><div><dt>Amount</dt><dd className="money">£2,500 GBP</dd></div></dl><p>Thank you — please let me know once the payment is sent.</p></div><div className="drawer-actions"><Button onClick={() => copy("message")}><Copy />{copied === "message" ? "Copied" : "Copy"}</Button><Button variant="outline" onClick={() => copy("email")}><Clipboard />{copied === "email" ? "Copied" : "Copy email version"}</Button><Button variant="ghost">Make it simpler</Button></div><p className="helper-text">Replace every placeholder with your own verified payment details before sending.</p></SheetContent></Sheet>
  </div>;
}

function RouteCard({ kind, data, flexible }: { kind: "best"; data: typeof immediate; flexible: boolean }) { return <article className="route-card primary-route"><div className="route-card-top"><span className="route-badge">BEST NOW</span><StatusBadge type="estimated" help="Timing and cost may vary by account and transaction." /></div><h2>{data.title}</h2><p>{data.reason}</p><div className="route-flow">{data.route.map((node, index) => <div key={node} className="route-flow-part"><span><Building2 />{node}</span>{index < data.route.length - 1 && <ArrowRight />}</div>)}</div><div className="route-metrics"><Metric label="Cost" value="Estimated" type="estimated" /><Metric label="Speed" value={flexible ? "Setup first" : "1–3 days"} type="estimated" /><Metric label="Keep foreign currency" value={flexible ? "Supported" : "Limited"} type="verified" /><Metric label="Payment records" value={flexible ? "Stronger setup" : "May need verification"} type={flexible ? "verified" : "needs"} /></div></article>; }
function LongTermCard() { return <article className="route-card long-term"><div className="route-card-top"><span className="route-badge soft">BEST LONG-TERM</span></div><h2>Meezan Freelancer Account + ESFCA</h2><p>{optimal.reason}</p><ul className="benefit-list"><li><Check />Keep foreign currency</li><li><Check />Islamic banking match</li><li><Check />Stronger export setup</li></ul><p className="term-helper"><strong>ESFCA</strong> is a linked account that can let eligible exporters retain part of their earnings in foreign currency.</p></article>; }
function Metric({ label, value, type }: { label: string; value: string; type: "verified" | "estimated" | "needs" }) { return <div><span>{label}</span><strong>{value}</strong><StatusBadge type={type} help={type === "verified" ? "Grounded in the current mock rule set." : type === "estimated" ? "This can vary by provider, account or timing." : "Your exact setup should be confirmed."} /></div>; }
function ToggleChip({ selected, onClick, children }: { selected: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" aria-pressed={selected} className={cn("toggle-chip", selected && "selected")} onClick={onClick}><span>{selected && <Check />}</span>{children}</button>; }
function PakistanContext() { const rows = [["PSEB", "Registered", "Relevant to your IT export profile.", "verified"], ["Service category", "IT / ITeS", "Detected from web development.", "detected"], ["Payment-purpose context", "9186", "A purpose code associated with freelance computer and information services.", "likely"], ["Foreign-currency retention", "Relevant", "Your preference makes freelancer account / ESFCA options more relevant.", "verified"], ["Islamic banking", "Preference matched", "Based on the product information in this mock.", "verified"], ["Tax", "Potential reduced treatment may be relevant", "Confirm your personal treatment with a qualified professional.", "needs"]] as const; return <div className="context-list">{rows.map(([label, value, helper, status]) => <div key={label}><div><span>{label}</span><strong className={label.includes("purpose") ? "money" : ""}>{value}</strong><p>{helper}</p></div><StatusBadge type={status} label={status === "verified" && label === "Foreign-currency retention" ? "Verified rule" : undefined} /></div>)}<p className="legal-note">Raasta provides informational guidance only. Tax and regulatory outcomes should be verified with qualified professionals or the relevant institution.</p></div>; }
function CostBreakdown() { return <div className="cost-grid">{[["Client sends", "£2,500"], ["Provider fee", "Estimated"], ["Bank / intermediary charges", "Variable"], ["FX effect", "Estimated"], ["Estimated amount received", "A range will appear when verified data is available"]].map(([label, value]) => <div key={label}><span>{label}</span><strong className={value.includes("£") ? "money" : ""}>{value}</strong></div>)}<p>Final fees and exchange rates depend on the provider, bank, account and transaction timing.</p></div>; }
function Alternative({ title, route, consider, notOne }: { title: string; route: string; consider: string; notOne: string }) { return <article className="alternative-card"><span>{title}</span><h3>{route}</h3><div><strong>Why consider it</strong><p>{consider}</p></div><div><strong>Why it wasn't #1</strong><p>{notOne}</p></div></article>; }
